### ISSUE TITLE
[CI] Modify `npm-audit.yml` To Include Email Alert if Security Vulnerability Is Found

### ISSUE THREAD

**Issue by MathiasSchindlerCPH** [SaleCheck/sale-check#40]
## Objective
Built email alerting system if security vulnerabilities are found in system. 

<details>
<summary>
Add this part to existing `npm-audit.yml` to include email alerting:
</summary>

```yaml
jobs:
  npm-audit:
    # your existing npm-audit job here
    # ...

  notify-on-failure:
    runs-on: ubuntu-latest
    needs: npm-audit
    if: failure()  # runs only if npm-audit fails
    steps:
      - name: Send failure email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.example.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}   # yourname@gmail.com
          password: ${{ secrets.SMTP_PASSWORD }}   # Gmail App Password
          subject: "GitHub Action Failed: npm audit Security Scan"
          to: your-email@example.com
          from: ${{ secrets.SMTP_USERNAME }}   # yourname@gmail.com
          body: |
            The npm audit security scan job has failed.
            Please check the details in the Actions tab of your repository.
```
NB: Add this only to `deploy-functions-on-merge.yml` and `deploy-hosting-on-merge.yml`, since we don't want emails for every failed `npm audit`s on Pull Requests that are not merged yet.

</details>

## Reasoning 
Currently, failures in the `npm-audit` job may go unnoticed if not regularly monitored. Sending an email alert directly notifies the responsible parties without relying solely on manual checks or GitHub notification settings.

## Tasks
- [x] Set up SMTP credentials (e.g., Gmail SMTP or your own SMTP server) as GitHub secrets (`SMTP_USERNAME`, `SMTP_PASSWORD`).
  - _NB: Replace `smtp.example.com`, ports, and emails with your actual info._
- [x] This job will only run if the `npm-audit` job fails, and send you an email alert with basic info.
