### ISSUE TITLE
[CI] Add Code Linting Step to CI/CD Pipeline

### ISSUE THREAD

**Issue by MathiasSchindlerCPH** [SaleCheck/sale-check#43]
## Objective  
Add a code linting step to the CI/CD pipeline to ensure code quality and enforce consistent coding standards during development.

<details>  
<summary>  
Create new GitHub Action (e.g. `npm-run-lint.yml`):
</summary>

```yaml
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint
```
</details>

## Reasoning 
Adding linting to the CI/CD pipeline ensures code adheres to defined standards and helps catch syntax issues and bad patterns early in the development process. This promotes cleaner, more maintainable code and reduces the chances of preventable bugs making it into production.

## Tasks
- [ ] Configure linter for the project - e.g. `ESLint`.
- [ ] Define a corresponding npm script:
  ```json
  "scripts": {
    "lint": "eslint ."
  }
  ```
- [ ] Update main CI/CD pipelines to include linter before integrations tests. Add to workflows:
  - [`.github/workflows/deploy-functions-on-merge.yml`](https://github.com/SaleCheck/sale-check/blob/main/.github/workflows/deploy-functions-on-merge.yml)
  - [`.github/workflows/deploy-hosting-on-merge.yml`](https://github.com/SaleCheck/sale-check/blob/main/.github/workflows/deploy-hosting-on-merge.yml)
